### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/eris#1]
These are the milestones for eris - our Hackathon discord bot
Project Lead: @tatiaris 

(make separate issues for specific things)

- [ ] Room creation
- [ ] Tracking
    - [ ] Storing in db and stuff 
- [ ] Automated announcements for each event
- [ ] Remind me for this event

**Comment by tatiaris** [comment]
Helpful links:
discord.js documentation: https://discord.js.org/#/docs/main/stable/general/welcome
